### PR TITLE
Improve current PRs logging

### PR DESCRIPTION
**Pull request by simahawk**
* add `collect_prs_info` to retrieve all PRs details
* base `show_closed_prs` on it
* add `show_all_prs` to view them all at glance

### CODE REVIEW

**Comment by yvaucher** [comment]
Seems travis error is not related.

```
RuntimeError: Python 3.4 or later is required
The command "flake8 . --exclude=__init__.py" exited with 1.
```

**Comment by sbidoul** [comment]
@simahawk I finished this at 2307e751c6ccf9dbcae5b5c1e0156181ee87d4c7.

Can you re-test. Then I'll release.

**Comment by simahawk** [comment]
@sbidoul seems good :+1:

**Comment by sbidoul** [comment]
released

**Pull request merged**
