### PR TITLE
Add --force flag

### PR DESCRIPTION
**Pull request by Yajo**
If that flag is set, dirty repositories will fail to aggregate.

Set it to preserve old behavior of performing a hard reset on them before aggregating.

@Tecnativa

### CODE REVIEW

**Comment by Yajo** [comment]
Hi there @lmignon, just a little ping in case this got lost among yesterday's github failure.

**Comment by lmignon** [comment]
@Yajo Indeed, I've received a notification yesterday but the link was broken

**Comment by Yajo** [comment]
Sorry for the slow response.

- Tests that were failed honored or patched.
- New test.
- Actual code was wrong, fixed.
- Untracked file cleanup added.

**Comment by Yajo** [comment]
Should I rebase then?

**Comment by Yajo** [comment]
Done, thanks.

**Comment by Yajo** [comment]
Good, thanks to you :blush: 

Can we merge then? (And if you push a release I'd be really grateful)

**Comment by lmignon** [comment]
@Yajo done and published on pypi :smirk:

**Pull request merged**
