### PR TITLE
[IMP] Add multiprocessing option for aggregation

### PR DESCRIPTION
**Pull request by lasley**
This PR adds a multiprocessing pool for the repo aggregation if desired. 

I am still testing this, but wanted to submit the PR early to make sure there's not somewhere else you'd rather I put this. The reasoning I'm thinking that might be the case is because it seems the method I modified is untested (at least directly), so I'm thinking it's not important. 

* Move repo aggregation into a helper method
* Add option for the amount of processes to use when aggregating
* Use multiprocessing pool for aggregation if aforementioned option is enabled

### CODE REVIEW

**Comment by crimoniv** [comment]
I also think it would be interesting to have this option, as maintaining a large amount of repositories highly increases the execution time (even though some of them are only a few KBs).

**Comment by sbidoul** [comment]
I'm personally fine with the principle of this PR. One must examine why travis is red though.

**Comment by crimoniv** [comment]
I've submitted some changes to the main PR branch (https://github.com/LasLabs/git-aggregator/pull/1), feel free to comment or suggest any change.

Cheers!

**Comment by crimoniv** [comment]
Done! No more Travis errors :ok_hand:

**Comment by crimoniv** [comment]
We would love to see this feature being added to the main branch, would you mind if I open a new PR including our latest changes?

**Comment by sbidoul** [comment]
Hi, I had not noticed it's green now. I'm personally fine with this approach. Feel free to open another PR.

cc/ @lmignon

**Comment by sbidoul** [comment]
BTW, I just notice https://github.com/LasLabs/git-aggregator/pull/1 is much more complex than this one. What was not working with this PR?

**Comment by sbidoul** [comment]
Superseded by #21

**Pull request closed without merging**
